name: Manual run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: What url will be used?
        default: "http://www.swtestacademy.com"
      browser:
        required: true
        description: Which browser to use for testing?
        type: choice
        options:
          - chrome
          - firefox
          - edge
        default: "chrome"

jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: |
          cd test
          npm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run cypress
        env:
          URL: ${{github.event.inputs.url}}
        run: |
          cd test
          npx cypress run --browser ${{github.event.inputs.browser}}

      - name: Screenshot Upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: test/screenshots

      - name: Publish results to Slack if Test Fails
        uses: slackapi/slack-github-action@v1.24.0
        if: failure()
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
