name: Manual run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: What url will be used?
        default: "http://www.swtestacademy.com"
      chrome:
        type: boolean
        description: Run tests in Chrome
        default: true
      firefox:
        type: boolean
        description: Run tests in Firefox
        default: false
      edge:
        type: boolean
        description: Run tests in Edge
        default: false

jobs:
  chrome:
    name: Chrome Tests
    if: ${{ github.event.inputs.chrome == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: |
          cd test
          npm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run cypress
        env:
          URL: ${{github.event.inputs.url}}
        run: |
          cd test
          npx cypress run --browser chrome

      - name: Screenshot Upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: test/screenshots

      - name: Publish results to Slack if Test Fails
        uses: slackapi/slack-github-action@v1.24.0
        if: failure()
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\nBrowser: chrome\nURL: ${{github.event.inputs.url}}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}

  firefox:
    name: Firefox Tests
    if: ${{ github.event.inputs.firefox == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: |
          cd test
          npm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run cypress
        env:
          URL: ${{github.event.inputs.url}}
        run: |
          cd test
          npx cypress run --browser firefox

      - name: Screenshot Upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-firefox
          path: test/screenshots

      - name: Publish results to Slack if Test Fails
        uses: slackapi/slack-github-action@v1.24.0
        if: failure()
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\nBrowser: firefox\nURL: ${{github.event.inputs.url}}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}

  edge:
    name: Edge Tests
    if: ${{ github.event.inputs.edge == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: |
          cd test
          npm install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/cypress.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Run cypress
        env:
          URL: ${{github.event.inputs.url}}
        run: |
          cd test
          npx cypress run --browser edge

      - name: Screenshot Upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-edge
          path: test/screenshots

      - name: Publish results to Slack if Test Fails
        uses: slackapi/slack-github-action@v1.24.0
        if: failure()
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\nBrowser: edge\nURL: ${{github.event.inputs.url}}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEB_HOOK }}
